declare module '@sketchpixy/rubix'{ 
    // extended bootstrap component
    import * as bootstrap from "react-bootstrap"
    
    export class Accordion extends bootstrap.Accordion{}
    export interface AccordionProps extends bootstrap.AccordionProps{}
    export class Alert extends bootstrap.Alert{}
    export interface AlertProps extends bootstrap.AlertProps{}
    export class Badge extends bootstrap.Badge{}
    export interface BadgeProps extends bootstrap.BadgeProps{}
    export class Breadcrumb extends bootstrap.Breadcrumb{}
    export interface BreadcrumbProps extends bootstrap.BreadcrumbProps{}
    export class BreadcrumbItem extends bootstrap.BreadcrumbItem{}
    export interface BreadcrumbItemProps extends bootstrap.BreadcrumbItemProps{}
    export class Button extends bootstrap.Button{}
    export interface ButtonProps extends bootstrap.ButtonProps{}
    export class ButtonGroup extends bootstrap.ButtonGroup{}
    export interface ButtonGroupProps extends bootstrap.ButtonGroupProps{}
    export class ButtonToolbar extends bootstrap.ButtonToolbar{}
    export interface ButtonToolbarProps extends bootstrap.ButtonToolbarProps{}
    export class Carousel extends bootstrap.Carousel{}
    export interface CarouselProps extends bootstrap.CarouselProps{}
    export class CarouselCaption extends bootstrap.CarouselCaption{}
    export interface CarouselCaptionProps extends bootstrap.CarouselCaptionProps{}
    export class CarouselItem extends bootstrap.CarouselItem{}
    export interface CarouselItemProps extends bootstrap.CarouselItemProps{}
    export class Checkbox extends bootstrap.Checkbox{}
    export interface CheckboxProps extends bootstrap.CheckboxProps{}
    export class Clearfix extends bootstrap.Clearfix{}
    export interface ClearfixProps extends bootstrap.ClearfixProps{}
    export class Col extends bootstrap.Col{}
    export interface ColProps extends bootstrap.ColProps{}
    export class Collapse extends bootstrap.Collapse{}
    export interface CollapseProps extends bootstrap.CollapseProps{}
    export class ControlLabel extends bootstrap.ControlLabel{}
    export interface ControlLabelProps extends bootstrap.ControlLabelProps{}
    export class Dropdown extends bootstrap.Dropdown{}
    export interface DropdownProps extends bootstrap.DropdownProps{}
    export class DropdownButton extends bootstrap.DropdownButton{}
    export interface DropdownButtonProps extends bootstrap.DropdownButtonProps{}
    export class DropdownMenu extends bootstrap.DropdownMenu{}
    export interface DropdownMenuProps extends bootstrap.DropdownMenuProps{}
    export class DropdownToggle extends bootstrap.DropdownToggle{}
    export interface DropdownToggleProps extends bootstrap.DropdownToggleProps{}
    export class Fade extends bootstrap.Fade{}
    export interface FadeProps extends bootstrap.FadeProps{}
    export class Form extends bootstrap.Form{}
    export interface FormProps extends bootstrap.FormProps{}
    export class FormControl extends bootstrap.FormControl{}
    export interface FormControlProps extends bootstrap.FormControlProps{}
    export class FormControlFeedback extends bootstrap.FormControlFeedback{}
    // export class FormControlFeedbackProp extends bootstrap.FormControlFeedbackProp{}
    export class FormControlStatic extends bootstrap.FormControlStatic{}
    export interface FormControlStaticProps extends bootstrap.FormControlStaticProps{}
    export class FormGroup extends bootstrap.FormGroup{}
    export interface FormGroupProps extends bootstrap.FormGroupProps{}
    export class Glyphicon extends bootstrap.Glyphicon{}
    export interface GlyphiconProps extends bootstrap.GlyphiconProps{}
    export class Grid extends bootstrap.Grid{}
    export interface GridProps extends bootstrap.GridProps{}
    export class HelpBlock extends bootstrap.HelpBlock{}
    export interface HelpBlockProps extends bootstrap.HelpBlockProps{}
    export class Image extends bootstrap.Image{}
    export interface ImageProps extends bootstrap.ImageProps{}
    export class InputGroup extends bootstrap.InputGroup{}
    export interface InputGroupProps extends bootstrap.InputGroupProps{}
    export class InputGroupAddon extends bootstrap.InputGroupAddon{}
    export interface InputGroupAddonProps extends bootstrap.InputGroupAddonProps{}
    export class InputGroupButton extends bootstrap.InputGroupButton{}
    export interface InputGroupButtonProps extends bootstrap.InputGroupButtonProps{}
    export class Jumbotron extends bootstrap.Jumbotron{}
    export interface JumbotronProps extends bootstrap.JumbotronProps{}
    export class Label extends bootstrap.Label{}
    export interface LabelProps extends bootstrap.LabelProps{}
    export class ListGroup extends bootstrap.ListGroup{}
    export interface ListGroupProps extends bootstrap.ListGroupProps{}
    export class ListGroupItem extends bootstrap.ListGroupItem{}
    export interface ListGroupItemProps extends bootstrap.ListGroupItemProps{}
    export class Media extends bootstrap.Media{}
    export interface MediaProps extends bootstrap.MediaProps{}
    export class MediaBody extends bootstrap.MediaBody{}
    export interface MediaBodyProps extends bootstrap.MediaBodyProps{}
    export class MediaHeading extends bootstrap.MediaHeading{}
    export interface MediaHeadingProps extends bootstrap.MediaHeadingProps{}
    export class MediaLeft extends bootstrap.MediaLeft{}
    export interface MediaLeftProps extends bootstrap.MediaLeftProps{}
    export class MediaList extends bootstrap.MediaList{}
    export interface MediaListProps extends bootstrap.MediaListProps{}
    export class MediaListItem extends bootstrap.MediaListItem{}
    export interface MediaListItemProps extends bootstrap.MediaListItemProps{}
    export class MediaRight extends bootstrap.MediaRight{}
    export interface MediaRightProps extends bootstrap.MediaRightProps{}
    export class MenuItem extends bootstrap.MenuItem{}
    export interface MenuItemProps extends bootstrap.MenuItemProps{}
    export class Modal extends bootstrap.Modal{}
    export interface ModalProps extends bootstrap.ModalProps{}
    export class ModalBody extends bootstrap.ModalBody{}
    export interface ModalBodyProps extends bootstrap.ModalBodyProps{}
    export class ModalDialog extends bootstrap.ModalDialog{}
    export interface ModalDialogProps extends bootstrap.ModalDialogProps{}
    export class ModalFooter extends bootstrap.ModalFooter{}
    export interface ModalFooterProps extends bootstrap.ModalFooterProps{}
    export class ModalHeader extends bootstrap.ModalHeader{}
    export interface ModalHeaderProps extends bootstrap.ModalHeaderProps{}
    export class ModalTitle extends bootstrap.ModalTitle{}
    export interface ModalTitleProps extends bootstrap.ModalTitleProps{}
    export class Nav extends bootstrap.Nav{}
    export interface NavProps extends bootstrap.NavProps{}
    export class Navbar extends bootstrap.Navbar{}
    export interface NavbarProps extends bootstrap.NavbarProps{}
    export class NavbarBrand extends bootstrap.NavbarBrand{}
    export interface NavbarBrandProps extends bootstrap.NavbarBrandProps{}
    export class NavbarCollapse extends bootstrap.NavbarCollapse{}
    export interface NavbarCollapseProps extends bootstrap.NavbarCollapseProps{}
    export class NavbarHeader extends bootstrap.NavbarHeader{}
    export interface NavbarHeaderProps extends bootstrap.NavbarHeaderProps{}
    export class NavbarToggle extends bootstrap.NavbarToggle{}
    export interface NavbarToggleProps extends bootstrap.NavbarToggleProps{}
    export class NavDropdown extends bootstrap.NavDropdown{}
    export interface NavDropdownProps extends bootstrap.NavDropdownProps{}
    export class NavItem extends bootstrap.NavItem{}
    export interface NavItemProps extends bootstrap.NavItemProps{}
    export class Overlay extends bootstrap.Overlay{}
    export interface OverlayProps extends bootstrap.OverlayProps{}
    export class OverlayTrigger extends bootstrap.OverlayTrigger{}
    export interface OverlayTriggerProps extends bootstrap.OverlayTriggerProps{}
    export class PageHeader extends bootstrap.PageHeader{}
    export interface PageHeaderProps extends bootstrap.PageHeaderProps{}
    export class PageItem extends bootstrap.PageItem{}
    export interface PageItemProps extends bootstrap.PageItemProps{}
    export class Pager extends bootstrap.Pager{}
    export interface PagerProps extends bootstrap.PagerProps{}
    export class PagerItem extends bootstrap.PagerItem{}
    export interface PagerItemProps extends bootstrap.PagerItemProps{}
    export class Pagination extends bootstrap.Pagination{}
    export interface PaginationProps extends bootstrap.PaginationProps{}
    export class PaginationItem extends bootstrap.PaginationItem{}
    export interface PaginationItemProps extends bootstrap.PaginationItemProps{}
    export class Panel extends bootstrap.Panel{}
    export interface PanelProps extends bootstrap.PanelProps{}
    export class PanelHeading extends bootstrap.PanelHeading{}
    export interface PanelHeadingProps extends bootstrap.PanelHeadingProps{}
    export class PanelTitle extends bootstrap.PanelTitle{}
    export interface PanelTitleProps extends bootstrap.PanelTitleProps{}
    export class PanelToggle extends bootstrap.PanelToggle{}
    export interface PanelToggleProps extends bootstrap.PanelToggleProps{}
    export class PanelCollapse extends bootstrap.PanelCollapse{}
    export interface PanelCollapseProps extends bootstrap.PanelCollapseProps{}
    export class PanelBody extends bootstrap.PanelBody{}
    export interface PanelBodyProps extends bootstrap.PanelBodyProps{}
    export class PanelFooter extends bootstrap.PanelFooter{}
    export interface PanelFooterProps extends bootstrap.PanelFooterProps{}
    export class PanelGroup extends bootstrap.PanelGroup{}
    export interface PanelGroupProps extends bootstrap.PanelGroupProps{}
    export class Popover extends bootstrap.Popover{}
    export interface PopoverProps extends bootstrap.PopoverProps{}
    export class ProgressBar extends bootstrap.ProgressBar{}
    export interface ProgressBarProps extends bootstrap.ProgressBarProps{}
    export class Radio extends bootstrap.Radio{}
    export interface RadioProps extends bootstrap.RadioProps{}
    export class ResponsiveEmbed extends bootstrap.ResponsiveEmbed{}
    export interface ResponsiveEmbedProps extends bootstrap.ResponsiveEmbedProps{}
    export class Row extends bootstrap.Row{}
    export interface RowProps extends bootstrap.RowProps{}
    export class SafeAnchor extends bootstrap.SafeAnchor{}
    export interface SafeAnchorProps extends bootstrap.SafeAnchorProps{}
    export class SplitButton extends bootstrap.SplitButton{}
    export interface SplitButtonProps extends bootstrap.SplitButtonProps{}
    export class SplitToggle extends bootstrap.SplitToggle{}
    export interface SplitToggleProps extends bootstrap.SplitToggleProps{}
    export class Tab extends bootstrap.Tab{}
    export interface TabProps extends bootstrap.TabProps{}
    export class TabContainer extends bootstrap.TabContainer{}
    export interface TabContainerProps extends bootstrap.TabContainerProps{}
    export class TabContent extends bootstrap.TabContent{}
    export interface TabContentProps extends bootstrap.TabContentProps{}
    export class Table extends bootstrap.Table{}
    export interface TableProps extends bootstrap.TableProps{}
    export class TabPane extends bootstrap.TabPane{}
    export interface TabPaneProps extends bootstrap.TabPaneProps{}
    export class Tabs extends bootstrap.Tabs{}
    export interface TabsProps extends bootstrap.TabsProps{}
    export class Thumbnail extends bootstrap.Thumbnail{}
    export interface ThumbnailProps extends bootstrap.ThumbnailProps{}
    export class ToggleButton extends bootstrap.ToggleButton{}
    export interface ToggleButtonProps extends bootstrap.ToggleButtonProps{}
    export class ToggleButtonGroup extends bootstrap.ToggleButtonGroup{}
    export class Tooltip extends bootstrap.Tooltip{}
    export interface TooltipProps extends bootstrap.TooltipProps{}
    export class Well extends bootstrap.Well{}
    export interface WellProps extends bootstrap.WellProps{}

    // rubix component
    export class MainContainer extends React.Component<React.HTMLProps<React.Component>>{}
    export class PanelContainer extends React.Component<React.HTMLProps<React.Component>>{}
    export class PanelTabContainer extends bootstrap.TabContainer{}
    export class PanelHeader extends bootstrap.PanelFooter{}
    export class PanelLeft extends bootstrap.PanelBody{}
    export class PanelRight extends bootstrap.PanelBody{}
}

